name: Remote Dispatch

on:
  workflow_dispatch:

# curl \
# -X POST \
# -H "Accept: application/vnd.github.v3+json" \
# https://api.github.com/repos/thewrightmatt/diffie-spoon/dispatches \
# -d '{"event_type":"release"}'
jobs:
  remote-run:
    runs-on: ubuntu-latest
    steps:
    - name: Kick off remote
      env: 
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $TOKEN \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/OWNER/REPO/dispatches \
        -d '{"event_type":"release"}'