name: Remote Dispatch

on:
  workflow_dispatch:

jobs:
  remote-run:
    runs-on: ubuntu-latest
    steps:
    - name: Kick off remote
      env: 
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer "$TOKEN" \
        https://api.github.com/repos/thewrightmatt/diffie-spoon \
        -d '{"event_type":"release"}'